### ISSUE TITLE
after lvl 3 of main story (new hope) mod breaks?

### ISSUE THREAD

**Issue by aow-lizardshaman** [magu5026/FasterStart#1]
when i go to start lvl 3 and lvl 4 it gives me this error
Error while running on_init: __FasterStart__/control.lua:50: attempt to index local 'A_Grid' (a nil value)
why is this happening?

**Comment by mgrubb** [comment]
I had this issue as well, after digging in the code a bit, the mod assumes that there is no existing armor equipped.  When beginning a brand new game when the mode inserts the small armor item, it is auto-equipped and so then it works.  The work around is to un-equip any existing armor save your game, and re-enable the mod.
